let supabaseClient=null,currentUser=null,currentActivity=null,currentReport=null,profile={name:'',school:'',logo:''};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showView(name){['login','register','forgot','reset'].forEach(v=>$(v+'Panel').classList.toggle('hidden',v!==name));$('authMessage').classList.add('hidden')}
function msg(text){$('authMessage').textContent=text;$('authMessage').classList.remove('hidden')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
async function init(){try{const c=await fetch('/api/config').then(r=>r.json());if(!c.supabaseUrl||!c.supabaseAnonKey)throw 0;supabaseClient=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);supabaseClient.auth.onAuthStateChange((e,s)=>{if(e==='PASSWORD_RECOVERY')showView('reset');else updateSession(s?.user||null)});const {data}=await supabaseClient.auth.getSession();updateSession(data.session?.user||null)}catch{msg('Configure SUPABASE_URL e SUPABASE_ANON_KEY no Vercel.')}}
function key(){return `aulafacil_profile_${currentUser?.id||'none'}`}
function updateSession(user){currentUser=user;if(!user){$('authScreen').classList.remove('hidden');$('app').classList.add('hidden');return}$('authScreen').classList.add('hidden');$('app').classList.remove('hidden');profile=JSON.parse(localStorage.getItem(key())||'{}');if(!profile.name)profile.name=user.user_metadata?.full_name||'';refreshProfile();if(!profile.school)setTimeout(()=>openProfile(),200)}
function refreshProfile(){$('welcomeName').textContent=profile.name||'Professor(a)';$('summarySchool').textContent=profile.school||'Configure seu perfil';$('profileName').value=profile.name||'';$('profileSchool').value=profile.school||'';['summaryLogo','logoPreview'].forEach(id=>{const el=$(id);if(profile.logo){el.src=profile.logo;el.style.display='block'}else el.style.display='none'})}
$('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)msg('E-mail ou senha incorretos.')};
$('registerForm').onsubmit=async e=>{e.preventDefault();if($('registerPassword').value!==$('registerConfirm').value)return msg('As senhas não são iguais.');const {data,error}=await supabaseClient.auth.signUp({email:$('registerEmail').value.trim(),password:$('registerPassword').value,options:{data:{full_name:$('registerName').value.trim()},emailRedirectTo:location.origin}});if(error)return msg(error.message);if(!data.session){showView('login');msg('Conta criada. Confirme seu e-mail para entrar.')}};
$('forgotForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.resetPasswordForEmail($('forgotEmail').value.trim(),{redirectTo:location.origin});msg(error?error.message:'Link enviado para seu e-mail.')};
$('resetForm').onsubmit=async e=>{e.preventDefault();if($('resetPassword').value!==$('resetConfirm').value)return msg('As senhas não são iguais.');const {error}=await supabaseClient.auth.updateUser({password:$('resetPassword').value});msg(error?error.message:'Senha alterada com sucesso.')};
$('logoutBtn').onclick=()=>supabaseClient.auth.signOut();
function openProfile(){$('profileModal').classList.remove('hidden');refreshProfile()} $('profileBtn').onclick=openProfile;$('closeProfile').onclick=()=>{$('profileModal').classList.add('hidden')};
$('profileLogo').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>1200000)return alert('Escolha uma imagem com até 1,2 MB.');const r=new FileReader();r.onload=()=>{profile.logo=r.result;$('logoPreview').src=r.result;$('logoPreview').style.display='block'};r.readAsDataURL(f)};
$('profileForm').onsubmit=e=>{e.preventDefault();profile.name=$('profileName').value.trim();profile.school=$('profileSchool').value.trim();localStorage.setItem(key(),JSON.stringify(profile));refreshProfile();$('profileModal').classList.add('hidden')};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));$('activityPage').classList.toggle('hidden',b.dataset.page!=='activity');$('reportPage').classList.toggle('hidden',b.dataset.page!=='report')});
function logoHtml(){return profile.logo?`<img src="${profile.logo}" alt="Logo">`:`<div style="width:72px;height:72px;border:1px dashed #aaa;display:grid;place-items:center;font-size:11px">LOGO</div>`}
function headerHtml(extra=''){return `<div class="worksheet-head">${logoHtml()}<div><h2>${esc(profile.school||'Nome da escola')}</h2><p>Professor(a): <strong>${esc(profile.name||'Professor(a)')}</strong></p>${extra}</div></div>`}
function demoActivity(p){let qs=[];for(let i=1;i<=p.quantity;i++){let prompt,answer,options=null;if(p.subject==='Matemática'){let a=i+3,b=(i%6)+2;prompt=`Resolva: ${a} × ${b} =`;answer=String(a*b)}else{prompt=`Explique um aspecto importante de ${p.topic}.`;answer=`Resposta coerente sobre ${p.topic}, adequada ao ${p.grade}.`}if(p.questionType==='Objetiva'||(p.questionType==='Mista'&&i%2===0))options=p.subject==='Matemática'?[answer,String(Number(answer)+2),String(Number(answer)+5),String(Math.max(0,Number(answer)-2))]:['Resposta correta','Alternativa incorreta','Outra alternativa','Nenhuma das anteriores'];qs.push({number:i,prompt,answer,options,visualSupport:p.illustrations==='none'?'':`Apoio visual sugerido: imagem simples relacionada a ${p.topic}.`})}return{title:`Atividade de ${p.subject} — ${p.topic}`,instructions:p.autism==='no'?'Leia com atenção e responda.':'Faça uma questão por vez. Leia o comando curto e marque ou escreva a resposta.',subject:p.subject,grade:p.grade,difficulty:p.difficulty,questions:qs}}
$('activityForm').onsubmit=async e=>{e.preventDefault();if(!profile.name||!profile.school)return openProfile();const p={subject:$('subject').value,grade:$('grade').value,topic:$('topic').value.trim(),quantity:Number($('quantity').value),difficulty:$('difficulty').value,questionType:$('questionType').value,printStyle:$('printStyle').value,illustrations:$('illustrations').value,autism:$('autism').value,extraInstructions:$('extra').value.trim()};$('generateBtn').disabled=true;$('generateBtn').textContent='Gerando...';try{const r=await fetch('/api/generate-activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw 0;currentActivity=await r.json()}catch{currentActivity=demoActivity(p)}finally{$('generateBtn').disabled=false;$('generateBtn').textContent='Gerar atividade'}renderActivity()};
function renderActivity(){const a=currentActivity;const q=a.questions.map(x=>`<div class="question"><strong>${x.number}. ${esc(x.prompt)}</strong>${x.visualSupport?`<div style="border:1px dashed #aaa;padding:10px;margin-top:8px;font-size:12px">${esc(x.visualSupport)}</div>`:''}${x.options?`<div class="options">${x.options.map((o,i)=>`<span>(${String.fromCharCode(65+i)}) ${esc(o)}</span>`).join('')}</div>`:'<div class="answer-lines"></div>'}</div>`).join('');$('studentPreview').innerHTML=`${headerHtml()}<div class="student-fields"><div class="line">Aluno(a):</div><div class="line">Data:</div></div><div class="paper-title"><h2>${esc(a.title)}</h2><p>${esc(a.grade)} • ${esc(a.difficulty||'')}</p></div><p><strong>Orientações:</strong> ${esc(a.instructions)}</p>${q}`;$('teacherPreview').innerHTML=`${headerHtml('<span class="exclusive">USO EXCLUSIVO DO PROFESSOR</span>')}<div class="paper-title"><h2>Gabarito — ${esc(a.title)}</h2></div>${a.questions.map(x=>`<p><strong>${x.number}.</strong> ${esc(x.answer)}</p>`).join('')}`;$('activityResult').classList.remove('hidden');$('activityResult').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('studentPreview').classList.toggle('hidden',b.dataset.tab!=='student');$('teacherPreview').classList.toggle('hidden',b.dataset.tab!=='teacher')});
function makePdf(elementId,file){const {jsPDF}=window.jspdf;const el=$(elementId);const doc=new jsPDF({unit:'pt',format:'a4'});doc.html(el,{callback:d=>d.save(file),x:25,y:25,width:545,windowWidth:794,html2canvas:{scale:.72,useCORS:true}})}
$('studentPdf').onclick=()=>makePdf('studentPreview','atividade-aluno.pdf');$('teacherPdf').onclick=()=>makePdf('teacherPreview','gabarito-professor.pdf');$('newActivity').onclick=()=>{$('activityResult').classList.add('hidden');$('activityForm').reset();scrollTo({top:0,behavior:'smooth'})};
$('reportForm').onsubmit=e=>{e.preventDefault();if(!profile.name||!profile.school)return openProfile();const d={type:$('reportType').value,clazz:$('reportClass').value,period:$('reportPeriod').value,student:$('reportStudent').value,situation:$('reportSituation').value,difficulties:$('reportDifficulties').value,actions:$('reportActions').value,results:$('reportResults').value,next:$('reportNext').value};currentReport=`Durante o período ${d.period}, na turma ${d.clazz}${d.student?`, com atenção ao(à) estudante ${d.student}`:''}, observou-se o seguinte: ${d.situation}\n\nAs principais dificuldades identificadas foram: ${d.difficulties||'não foram registradas dificuldades específicas'}.\n\nAs ações pedagógicas realizadas incluíram: ${d.actions||'acompanhamento contínuo e orientações em sala'}.\n\nQuanto aos resultados, percebeu-se: ${d.results||'a necessidade de continuidade do acompanhamento'}.\n\nComo encaminhamentos para o próximo período, recomenda-se: ${d.next||'manter o acompanhamento pedagógico e reavaliar as estratégias adotadas'}.`; $('reportPreview').innerHTML=`${headerHtml()}<div class="paper-title"><h2>${esc(d.type)}</h2><p>Turma: ${esc(d.clazz)} • Período: ${esc(d.period)}</p></div><div class="report-text">${esc(currentReport)}</div><div style="margin-top:70px;display:grid;grid-template-columns:1fr 1fr;gap:35px"><div class="line">Data:</div><div class="line">Assinatura:</div></div>`;$('reportResult').classList.remove('hidden');$('reportResult').scrollIntoView({behavior:'smooth'})};
$('reportPdf').onclick=()=>makePdf('reportPreview','relatorio-ac.pdf');$('newReport').onclick=()=>{$('reportResult').classList.add('hidden');$('reportForm').reset()};
init();
