-- PEDIDOFLOW 1.0 COMERCIAL
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase.

begin;

-- 1) Tabelas
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text default '',
  preco numeric(10,2) not null check (preco >= 0),
  categoria text default 'Outros',
  imagem_url text default '',
  ativo boolean default true,
  criado_em timestamptz default now()
);

create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  nome_loja text not null default 'PedidoFlow Lanches',
  whatsapp text not null default '',
  taxa_entrega numeric(10,2) default 5 check (taxa_entrega >= 0),
  endereco text default 'Jequié - BA',
  chave_pix text default '',
  loja_aberta boolean default true,
  atualizado_em timestamptz default now()
);

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text default '',
  role text not null default 'cliente' check (role in ('cliente','dono')),
  whatsapp text default '',
  aceita_promocoes boolean not null default false,
  consentimento_em timestamptz,
  criado_em timestamptz default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero integer not null,
  cliente_id uuid references auth.users(id) on delete set null,
  cliente_nome text not null,
  cliente_telefone text default '',
  tipo_entrega text not null default 'Entrega',
  endereco text default '',
  bairro text default '',
  referencia text default '',
  pagamento text default '',
  observacoes text default '',
  subtotal numeric(10,2) not null default 0,
  taxa_entrega numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'Recebido'
    check (status in ('Recebido','Preparando','Saiu para entrega','Finalizado','Cancelado')),
  itens jsonb not null default '[]'::jsonb,
  criado_em timestamptz default now()
);


-- Dados salvos do cliente
alter table public.perfis add column if not exists endereco text default '';
alter table public.perfis add column if not exists numero text default '';
alter table public.perfis add column if not exists bairro text default '';
alter table public.perfis add column if not exists referencia text default '';
alter table public.perfis add column if not exists cidade text default '';

-- 2) Dados iniciais
insert into public.configuracoes
(nome_loja, whatsapp, taxa_entrega, endereco, chave_pix, loja_aberta)
select 'PedidoFlow Lanches', '5573999999999', 5.00, 'Jequié - BA', '', true
where not exists (select 1 from public.configuracoes);

insert into public.produtos
(nome, descricao, preco, categoria, imagem_url, ativo)
select * from (
  values
  ('X-Burguer Clássico','Pão, carne artesanal, queijo, presunto, salada e molho especial.',18.90,'Hambúrgueres','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',true),
  ('X-Bacon Especial','Pão, carne artesanal, queijo, bacon crocante, salada e molho especial.',24.90,'Hambúrgueres','https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',true),
  ('X-Tudo da Casa','Carne, queijo, presunto, bacon, ovo, salada e molho da casa.',29.90,'Hambúrgueres','https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Calabresa','Molho de tomate, mussarela, calabresa, cebola e orégano.',42.00,'Pizzas','https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',true),
  ('Pizza Frango com Catupiry','Molho, mussarela, frango desfiado, catupiry e orégano.',46.00,'Pizzas','https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80',true),
  ('Coxinha de Frango','Coxinha crocante recheada com frango temperado.',7.00,'Salgados','https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=80',true),
  ('Pastel de Carne','Pastel crocante recheado com carne moída temperada.',9.00,'Salgados','https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=900&q=80',true),
  ('Batata Frita','Porção de batata frita crocante com molho especial.',16.00,'Porções','https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80',true),
  ('Refrigerante Lata','Refrigerante gelado, lata de 350 ml.',6.00,'Bebidas','https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=900&q=80',true),
  ('Suco Natural','Suco natural preparado na hora.',8.00,'Bebidas','https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80',true),
  ('Milk-shake Chocolate','Milk-shake cremoso de chocolate.',14.00,'Bebidas','https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=80',true),
  ('Brownie com Sorvete','Brownie de chocolate com sorvete de creme.',16.00,'Sobremesas','https://images.unsplash.com/photo-1564355808539-22fda35bed7e?auto=format&fit=crop&w=900&q=80',true)
) as demo(nome,descricao,preco,categoria,imagem_url,ativo)
where not exists (select 1 from public.produtos);

-- 3) Função segura para reconhecer o dono
create or replace function public.usuario_e_dono()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.perfis
    where id = auth.uid()
      and role = 'dono'
  );
$$;

revoke all on function public.usuario_e_dono() from public;
grant execute on function public.usuario_e_dono() to authenticated;

-- 4) RLS
alter table public.produtos enable row level security;
alter table public.configuracoes enable row level security;
alter table public.perfis enable row level security;
alter table public.pedidos enable row level security;

-- Produtos
drop policy if exists "Produtos visíveis publicamente" on public.produtos;
drop policy if exists "Dono cadastra produtos" on public.produtos;
drop policy if exists "Dono edita produtos" on public.produtos;
drop policy if exists "Dono exclui produtos" on public.produtos;

create policy "Produtos visíveis publicamente"
on public.produtos for select
to anon, authenticated
using (true);

create policy "Dono cadastra produtos"
on public.produtos for insert
to authenticated
with check (public.usuario_e_dono());

create policy "Dono edita produtos"
on public.produtos for update
to authenticated
using (public.usuario_e_dono())
with check (public.usuario_e_dono());

create policy "Dono exclui produtos"
on public.produtos for delete
to authenticated
using (public.usuario_e_dono());

-- Configurações
drop policy if exists "Configurações visíveis publicamente" on public.configuracoes;
drop policy if exists "Dono cadastra configurações" on public.configuracoes;
drop policy if exists "Dono edita configurações" on public.configuracoes;

create policy "Configurações visíveis publicamente"
on public.configuracoes for select
to anon, authenticated
using (true);

create policy "Dono cadastra configurações"
on public.configuracoes for insert
to authenticated
with check (public.usuario_e_dono());

create policy "Dono edita configurações"
on public.configuracoes for update
to authenticated
using (public.usuario_e_dono())
with check (public.usuario_e_dono());

-- Perfis
drop policy if exists "Usuário lê próprio perfil" on public.perfis;
drop policy if exists "Dono lê todos os perfis" on public.perfis;
drop policy if exists "Cliente cria próprio perfil" on public.perfis;
drop policy if exists "Cliente atualiza próprio perfil" on public.perfis;

create policy "Usuário lê próprio perfil"
on public.perfis for select
to authenticated
using (id = auth.uid());

create policy "Dono lê todos os perfis"
on public.perfis for select
to authenticated
using (public.usuario_e_dono());

create policy "Cliente cria próprio perfil"
on public.perfis for insert
to authenticated
with check (id = auth.uid() and role = 'cliente');

create policy "Cliente atualiza próprio perfil"
on public.perfis for update
to authenticated
using (id = auth.uid() and role = 'cliente')
with check (id = auth.uid() and role = 'cliente');

-- Pedidos
drop policy if exists "Qualquer pessoa cria pedido" on public.pedidos;
drop policy if exists "Cliente lê próprios pedidos" on public.pedidos;
drop policy if exists "Dono lê todos os pedidos" on public.pedidos;
drop policy if exists "Dono atualiza pedidos" on public.pedidos;

create policy "Qualquer pessoa cria pedido"
on public.pedidos for insert
to anon, authenticated
with check (true);

create policy "Cliente lê próprios pedidos"
on public.pedidos for select
to authenticated
using (cliente_id = auth.uid());

create policy "Dono lê todos os pedidos"
on public.pedidos for select
to authenticated
using (public.usuario_e_dono());

create policy "Dono atualiza pedidos"
on public.pedidos for update
to authenticated
using (public.usuario_e_dono())
with check (public.usuario_e_dono());

-- 5) Storage
insert into storage.buckets (id, name, public)
values ('produtos', 'produtos', true)
on conflict (id) do update set public = true;

drop policy if exists "Fotos públicas" on storage.objects;
drop policy if exists "Dono envia fotos" on storage.objects;
drop policy if exists "Dono remove fotos" on storage.objects;

create policy "Fotos públicas"
on storage.objects for select
to public
using (bucket_id = 'produtos');

create policy "Dono envia fotos"
on storage.objects for insert
to authenticated
with check (bucket_id = 'produtos' and public.usuario_e_dono());

create policy "Dono remove fotos"
on storage.objects for delete
to authenticated
using (bucket_id = 'produtos' and public.usuario_e_dono());

-- 6) Realtime sem erro de duplicidade
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'pedidos'
  ) then
    alter publication supabase_realtime add table public.pedidos;
  end if;
end $$;

commit;
